apiVersion: v1
kind: Secret
metadata:
  name: juicefs-sc-secret
  namespace: kube-system
type: Opaque
stringData:
  name: "ceph-bkt-630d0187-3ddf-43da-a5a7-e9dd764b92f4"   #自动生成
  metaurl: "redis://10.233.94.163"  #前面安装redis的svc地址
  storage: "s3"
  bucket: "http://10.233.165.142/ceph-bkt-630d0187-3ddf-43da-a5a7-e9dd764b92f4" #对象存储的地址及bucket,bucket需要提前创建
  access-key: "HSZ37MT6SWLMOHEPXR83"  #对象存储的access-key对应前面的
  secret-key: "Vy0jagykX7xbZa7XJ7yejSvJPGA4kUjvvjNQEkuU" #对象存储的secret-key对应前面的
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-sc
provisioner: csi.juicefs.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/node-publish-secret-name: juicefs-sc-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: juicefs-sc-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system

