kind: Service
apiVersion: v1
metadata:
  labels:
    name: juicefs-redis-svc
  name: juicefs-redis-svc
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    name: juicefs-redis

